### ISSUE TITLE
Missing `GC.@preserve`s?

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/Cbc.jl#100]
Cbc.jl doesn't have a single `GC.@preserve` statement, but post-0.6, I really think it should. What's preventing `prob` from being garbage collected in calls like

https://github.com/JuliaOpt/Cbc.jl/blob/220f0fa5d94a4382261e76fc473ec494dd85382a/src/CbcCInterface.jl#L270

?

**Comment by mlubin** [comment]
Last time I looked into this, I understood that function arguments are safe from GC collection. Has this changed?

**Comment by tkoolen** [comment]
Sorry, I didn't fully parse your message. 

> they can't be freed in the calling scope until after the function returns

This is definitely not true anymore in >0.6.

**Comment by tkoolen** [comment]
See e.g. https://discourse.julialang.org/t/properly-using-finalizer-ccall-cconvert-and-unsafe-convert/6183/10?u=tkoolen.

**Comment by tkoolen** [comment]
Maybe you read https://discourse.julialang.org/t/julia-v0-6-vs-v0-7-gc-behaviour/10002/6, but if that's still accurate, it's precedented on `@noinline`.

**Comment by leethargo** [comment]
I have not read all the links completely, but are you worried that `prob` will be GC'ed during, after, or even because of the call to `solve`, even though `prob` is still referenced in some outer scope?

**Comment by tkoolen** [comment]
A problem is that `prob::CbcModel` might actually *not* be referenced anymore in some outer scope after one of the `Cbc` function calls, at least not in any GC-visible way, which as of right now allows Julia to potentially run the `CbcModel` finalizer *before* the `ccall`, and the `ccall`s expect `prob.p` to be a valid pointer.

**Comment by leethargo** [comment]
Thanks for the clarification. I still can not imagine a scenario where this reference to `prob` is missing or "invisible", but I will read through the links in detail now.
