### ISSUE TITLE
Update MOI Interface to use LinQuadOptInterface

### ISSUE THREAD

**Issue by ndinsmore** [JuliaOpt/Cbc.jl#110]
Sould Cbc be updated to use LinQuadOptInterface for it's MOI Interface?   It looks like it could leverage  alot of what Clp.jl has done and would make maintaining and upgrading both easier.

Has this already been discussed?

**Comment by mlubin** [comment]
What are the current maintenance issues with the Cbc MOI wrapper and how would they be addressed by using LinQuadOptInterface? IMO using LinQuadOptInterface should not be the preferred choice for interfaces because it adds another layer between JuMP and the solver that's not as well documented as plain MOI.

**Comment by odow** [comment]
LinQuadOptInterface assumes that variables and constraints can be added on-demand. The Cbc C interface ([until recently](https://github.com/coin-or/Cbc/commit/fe86269e0452e3abed57c65722ef0e49ae29169b)) requires everything at once.

**Comment by ndinsmore** [comment]
I wouldn't say that there are any maintenance issues per se.  But in looking at capabilities CBC ~= GLPK, so while trying to figure out what it would take to add dual capability to Cbc, I was looking at GLPK and Clp both of which use LQOI.   Cbc has actually modeled it's interface after CLP so I thought I would ask.

**Comment by mlubin** [comment]
Supporting duals means implementing the [ConstraintDual](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.ConstraintDual) attribute. That's about it.

**Comment by mlubin** [comment]
We don't plan to rewrite the interface to LQOI. Both Gurobi and GLPK are moving away from LQOI.
