### ISSUE TITLE
Support SolveTime

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Cbc.jl#124]
See https://www.juliaopt.org/MathOptInterface.jl/v0.9.1/apireference/#MathOptInterface.SolveTime

**Comment by Wikunia** [comment]
Would it be sufficient to add a field `solveTime`  here: https://github.com/JuliaOpt/Cbc.jl/blob/45323a2c6af92c1b15dc250c0b2dc466d17b3992/src/MOI_wrapper.jl#L10
And measure the time here: https://github.com/JuliaOpt/Cbc.jl/blob/master/src/MOI_wrapper.jl#L538
using `time()` ?

**Comment by blegat** [comment]
The issue with this approach is that it may include some of Julia compilation time. It might be the only solution though if Cbc does not provide this info
