### ISSUE TITLE
How to set Cbc Parameters

### ISSUE THREAD

**Issue by lausilvag** [JuliaOpt/Cbc.jl#135]
Hi
I am trying to set parameters for Cbc Solver

Z_OP = Model(with_optimizer(Cbc.Optimizer))
    set_parameter(Z_OP, "preProcess", off)
    set_parameter(Z_OP, "CliqueCuts", Root)
error:
UndefVarError: Off not defined
UndefVarError: Root not defined

Does anyone know how to fix the error and where can I find updated information on the command lines?

Thank you

**Comment by odow** [comment]
Answered on Discourse: https://discourse.julialang.org/t/how-to-set-cbc-parameters/38516/3

Let's keep the discussion on Discourse if you have follow-up questions.
