### ISSUE TITLE
missing definition

### ISSUE THREAD

**Issue by ORESoftware** [JuliaOpt/Cbc.jl#29]
what's up brolini

in your one example

just FYI

MIPSolver will be undefined

I assume the way to solve this is to simply install MIPSolver with Pkg.add

and then declare it with

using MIPSolver

at the top of your .jl file

but since I am new to Julia and CBC, this is all guesswork on my part

thanks

here is the file I am talking about:

![image](https://cloud.githubusercontent.com/assets/11139560/7037795/0e7b005a-dd5d-11e4-8155-4fa5d054bf82.png)

**Comment by ORESoftware** [comment]
Well, I am having trouble finding how to define MIPSolver in the example ; could you please help with this? thanks

**Comment by ORESoftware** [comment]
I changed the file to:

using MathProgBase
using JuMP
using Cbc

function knapsack()
    f = Float64[3, 1, 2]
    A = [7. 3. 1.]
    capacity = 10.
    solution = mixintprog(-f, A, '<', capacity, 'I', 0, 1, MIPSolver(:Cbc,LogLevel=0))
    println("Solution status: ", solution.status)
    println("Optimal value: ", solution.objval) # should be -7
    print("Solution vector: ")
    show(solution.sol)
    println()

end

knapsack()

and this seems like it loads the correct dependencies. However, the program is just churning and burning, no output, CPU is HOT. what kind of example optimization problem did you feed us?

**Comment by mlubin** [comment]
Sorry about that, this example suffered from bitrot and wasn't being tested.

**Comment by ORESoftware** [comment]
np, saved the next person some time, thanks for fixing

it worked
