### ISSUE TITLE
Cbc Preprocessing error (Windows only?)

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Cbc.jl#30]
The following code reliably crashes Julia on Windows (both 7 and 8) as well as Julia 0.3.x and the latest 0.4. Cbc version 2.9.2 (and 2.9.1). Note that it has an extra unused variable in column 6. 

```
using Cbc
m = Cbc.CbcMathProgModel()
Cbc.CbcMathProgSolverInterface.loadproblem!(m, Array(Float64, (0,6)), zeros(6), ones(6), nothing, nothing, nothing, :Min)
Cbc.CbcMathProgSolverInterface.addsos1!(m, [1,2,3,4,5],[1., 2., 3., 4., 5.])
Cbc.CbcMathProgSolverInterface.optimize!(m)
```

The error is 

```
Assertion failed!
Program: C:\Julia\Julia-0.3.9\bin\julia.exe
File: CglPreProcess.cpp, Line 2353
Expression: numberProhibited_==oldModel->getNumCols()
```

Turning off presolve gets rid of the error (`m = Cbc.CbcMathProgModel(preprocess="off")`)

So, why does this only happen on Windows machines (doesn't occur on JuliaBox or Ubuntu. I haven't tried OSX)? Is it a Cbc issue or a Julia / Cbc issue?

**Comment by mlubin** [comment]
@tkelman and I looked into a similar error. Cbc happens to be compiled with assertions enabled on windows but not on other platforms. No idea if the assertion is bogus or if there's a deeper issue in Cbc. Best way to get a definitive answer is to ask on the cbc mailing list.

**Comment by odow** [comment]
Okay cheers

**Comment by tkelman** [comment]
If you built with `--enable-debug` you could probably reproduce this elsewhere. Looks like this one's coming from Cgl, so if the end result is needing to disable assertions in Cgl (or upgrading to a newer version if there's a bugfix somewhere) I can file the request on the opensuse build service to do that. Or let you know how to do it, if you'd like to go through the steps yourself.

**Comment by odow** [comment]
Its not actually a problem with my full model. I just came across it when playing around (with a small, moderately useless instance) when debugging an unrelated error and wondered about the cause. 

Is there a reason why assertions are not enabled on other platforms?

**Comment by tkelman** [comment]
> Is there a reason why assertions are not enabled on other platforms?

That's the default in the upstream COIN-OR configure scripts. Assertions are disabled by default if you do the standard `./configure && make` even on Windows, enabling assertions on the WinRPM binaries was an unforeseen side-effect of the opensuse build service pre-setting `CXXFLAGS` to some default value. Ref https://github.com/JuliaOpt/CoinOptServices.jl/issues/2 for the whole debugging story.

There still might be other distribution buildbots like debian or fedora that preset `CXXFLAGS`, it might be worth testing out their binaries in a docker container or something to see whether they also end up with assertions enabled. The previous issue that I found was happening in bonmin, which I think is only just making its way into distros, maybe not released versions yet.

**Comment by ns-1m** [comment]
Using Mac OS X (10.8.5), Julia v0.40, JuMP master and CBC Solver 2.9.8, I got no problem. Here is result below.
~~~
Cbc3007W No integer variables - nothing to do
~~~

**Comment by mlubin** [comment]
This will be resolved when we move to BinaryBuilder for the windows binaries.

**Comment by odow** [comment]
Woo! Pleased to see this finally resolved.

**Comment by lovasoa** [comment]
Has the underlying issue in cbc been fixed ? I hit the same error while investigating https://github.com/coin-or/Cbc/issues/376

**Comment by mlubin** [comment]
@lovasoa Are you sure you're in the right place? Your comment https://github.com/coin-or/Cbc/issues/376#issuecomment-802999074 says you're using a Rust interface. This is the Julia interface.

**Comment by mlubin** [comment]
(And no, I don't know that the underlying issue is solved. We worked around it by disabling assertions in our binaries.)

**Comment by lovasoa** [comment]
Yes, I'm talking about the underlying bug in cbc itself. I was asking if anyone here knew whether the bug in cbc had been fixed, or if it had at least been reported ?

**Comment by lovasoa** [comment]
In the best case, the assertion itself is wrong, but in the worst case, the assertion is correct and there is a bug elsewhere, in which case disabling assertions may be unsafe, potentially causing a memory corruption and a security vulnerability...

**Comment by mlubin** [comment]
My apologies, no, it's not fixed nor reported to my knowledge, although my knowledge is from 2015.
