### ISSUE TITLE
Possible problem with Windows binaries and multithreading

### ISSUE THREAD

**Issue by kkmann** [JuliaOpt/Cbc.jl#31]
Hey,

I ran into strange problems when solving large binary integer problems on Win 7. Problems with more than approximately 10.000 variables randomly crash with no error message (Cbc log does not mention problems either). The problem is not deterministic - I do run into it quite often though. 
I guess, the problem lies with Cbc not Cbc.jl, but maybe updating the binaries provided could help?
Smaller problems run perfectly fine and I could not reproduce the problem using only a single thread so far.

**Comment by mlubin** [comment]
The Cbc binaries are relatively up to date, cc @tkelman. Could you try writing out the model to an MPS or LP file and calling the cbc executable directly? My guess is that you'll see the same crashes. If so, you can report the issue to the cbc mailing list.

**Comment by tkelman** [comment]
The binary build info is here https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-Cbc - 2.9.2, relatively recent. Not hard to update though. The 32 bit binaries are done separately, same url but with 64 replaced by 32, and simple replacement in the spec file. I wouldn't be surprised if the combination of multithreading and using a dll build of all the Cbc libraries is not widely tested.

**Comment by kkmann** [comment]
Hmm, damn - got the same problem with threads = 1 just way slower x) 

I will try to extract an example that fails reasonably often and post it to the Cbc list.

**Comment by odow** [comment]
Closing as stale. Please re-open if this is still a problem and you have a reproducible example.
