### ISSUE TITLE
Build Error in OS X 10.8 and Julia v0.4

### ISSUE THREAD

**Issue by ns-1m** [JuliaOpt/Cbc.jl#34]
Hi,

I have been building glpk, cbc solver and scip in the mac os x 10.8 - macbookpro for a while (macbookpro retina mid 2012). It seems that homebrew in Julia has a problem. 

Here is the log below.
~~~~~~~
julia> Pkg.build("Cbc")
INFO: Building Homebrew
remote: Counting objects: 242, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 242 (delta 196), reused 221 (delta 175), pack-reused 0
Receiving objects: 100% (242/242), 30.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (196/196), completed with 48 local objects.
From https://github.com/Homebrew/homebrew
   30b1c47..d08692f  master     -> origin/master
HEAD is now at d08692f cern-ndiff: audit fixes
HEAD is now at d45fe22 Merge pull request #91 from staticfloat/staging
INFO: Building Cbc
Warning: You are using OS X 10.8.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing cbc from staticfloat/juliadeps
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
==> Downloading http://www.coin-or.org/download/source/Cbc/Cbc-2.9.7.tgz
Already downloaded: /Users/nsicad/Library/Caches/Homebrew.jl/cbc-2.9.7.tgz
==> ./configure --prefix=/Users/nsicad/.julia/v0.4/Homebrew/deps/usr/Cellar/cbc/2.9.7 --without-lapack --enable-cbc-parallel
Last 15 lines from /Users/nsicad/Library/Logs/Homebrew/cbc/01.configure:
checking build system type... i386-apple-darwin12.5.0
checking whether we want to compile in debug mode... no
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-4.2 accepts -g... yes
checking for gcc-4.2 option to accept ANSI C... none needed
configure: C compiler options are: -O3 -pipe -DNDEBUG -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragmas -Wno-long-long  
checking whether we are using the GNU C++ compiler... no
checking whether g++-4.2 accepts -g... no
checking whether C++ compiler g++-4.2 works... no
configure: error: failed to find a C++ compiler or C++ compiler g++-4.2 does not work

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-juliadeps/issues

Warning: You are using OS X 10.8.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
=================================[ ERROR: Cbc ]=================================

LoadError: failed process: Process(`/Users/nsicad/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/cbc`, ProcessExited(1)) [1]
while loading /Users/nsicad/.julia/v0.4/Cbc/deps/build.jl, in expression starting on line 63

================================================================================

=======================================================[ BUILD ERRORS ]========================================================

WARNING: Cbc had build errors.

 - packages with build errors remain installed in /Users/nsicad/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cbc")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================================

**Comment by mlubin** [comment]
There are no binaries provided for OS X 10.8 (10.9 is the oldest version with binaries). Do you have a compiler installed?

**Comment by ns-1m** [comment]
Yes.

~~~~~~
bash-3.2$ gcc --version
gcc (GCC) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~~~~~~~~~~~~
How can I use my compiled cbc solver?


bash-3.2$ cbc --version
Welcome to the CBC MILP Solver 
Version: Trunk (unstable) 
Build Date: Apr 18 2015 
Revision Number: 2180 

command line - cbc --version (default strategy 1)
No match for -version - ? for list of commands
CoinSolver takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
Coin:

**Comment by mlubin** [comment]
``DYLD_LIBRARY_PATH`` should point to the directories that contain ``libcbcsolver.dylib`` and ``libclp.dylib``. (After that, restart julia and run ``Pkg.build("Cbc")``.) This package doesn't use the ``cbc`` binary.

**Comment by ns-1m** [comment]
The current CBC solver build tools does not creates these 2 dynamic libraries libcbcsolver.dylib and libclp.dylib as you can in my previous posting here (in 2012)

http://list.coin-or.org/pipermail/cbc/2012-November/000973.html

I need advise how to create these 2 dynamic libraries libcbcsolver.dylib and libclp.dylib in configure script.

**Comment by mlubin** [comment]
The build system has changed since 2012, you should be able to copy the ``./configure

**Comment by ns-1m** [comment]
As you can see in the cbc -version logs that I posted I am not using 2012 configure. 2015 configure script  as shown here:

bash-3.2$ cbc --version
Welcome to the CBC MILP Solver
Version: Trunk (unstable)
Build Date: Apr 18 2015
Revision Number: 2180

**Comment by tkralphs** [comment]
When you compile with `--enable-debug`, static libraries are built by default. You should be able to force dynamic libraries with `--enable-shared --disable-static` or better yet, just don't use `--enable-debug`. In your initial post above, the compiler that's being found by `configure` is `gcc-4.2` and `configure` fails because this compiler is not behaving as it should. I suggest you update to a modern compiler. This should be easy with Homebrew. On all recent versions of OS X, Cbc is building fine:

https://travis-ci.org/coin-or/Cbc

**Comment by ns-1m** [comment]
OK. I need to overhaul / update OS X this mid 2012 macbookpro.

Thanks Ted.
