### ISSUE TITLE
cbc crashing on windows

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Cbc.jl#35]
Cbc has started crashing on all appveyor runs with the error:
```
Assertion failed!
Program: C:\projects\julia\bin\julia-debug.exe
File: /usr/i686-w64-mingw32/sys-root/mingw/include/coin/CbcOrClpParam.cpp, Line 3934
Expression: i < numberParameters
```
(Example: https://ci.appveyor.com/project/mlubin/jump-jl/build/1.0.1840/job/xqr4r8yuue54u5p3#L866)

Have there been any recent updates to the windows binaries?

CC @tkelman @emreyamangil

**Comment by tkelman** [comment]
Possibly https://build.opensuse.org/package/rdiff/windows:mingw:win64/mingw64-runtime?linkrev=base&rev=39. Will test reinstating the replacement of GCC dll's.

**Comment by tkelman** [comment]
Should get resolved by https://build.opensuse.org/package/rdiff/windows:mingw:win64/mingw64-runtime?linkrev=base&rev=40 in a few hours once everything is finished rebuilding upstream.

**Comment by emreyamangil** [comment]
Thanks!!

**Comment by mlubin** [comment]
Appears to be fixed, thanks!
