### ISSUE TITLE
logLevel = 0 prints too much

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Cbc.jl#41]
It's very talky on MIP problems

**Comment by chriscoey** [comment]
it happens on both mac and linux

**Comment by Wikunia** [comment]
It prints information about presolve would like to have them turned off as well.

**Comment by odow** [comment]
Given this is a Cbc option and not a Cbc.jl option, I don't think there is much we can do.

**Comment by odow** [comment]
Closing since I'm not sure there is anything actionable to do here on the Cbc.jl side.
