### ISSUE TITLE
Specify initial Integer solution to CBC

### ISSUE THREAD

**Issue by samiit** [JuliaOpt/Cbc.jl#43]
I'm trying to find how I can specify an initial integer solution to CBC within JuMP.

Currently, I see that CBC starts solving an MILP problem after solving the relaxed problem. But in my problem, if I just do a constraint satisfaction (no objective), I'm getting an integer solution to the variables, which I would like CBC to improve upon. Otherwise, with the full objective (involving all variables, that are in the constraint), I'm not finding even a single integer solution.

Is there a way to do this in Cbc.jl?

Thanks,
Sam

**Comment by mlubin** [comment]
http://www.juliaopt.org/JuMP.jl/0.16/refvariable.html. Use ``setvalue`` to specify initial solutions. Cbc ignores incomplete solutions, so you have to specify a value for every variable in the model.

**Comment by samiit** [comment]
Thanks.
