### ISSUE TITLE
Pkg.build errors 

### ISSUE THREAD

**Issue by yuzhangbit** [JuliaOpt/Cbc.jl#48]
OS: ubuntu 16.04 
Julia version: 0.5.1 

When I run 
```julia
Pkg.add("Cbc")
Pkg.build("Cbc")
```
I get the error output below:
```
make[4]: Entering directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Osi'
PKG_CONFIG_PATH=/home/robot/.julia/v0.5/Cbc/deps/usr/lib64/pkgconfig:/home/robot/.julia/v0.5/Cbc/deps/usr/lib/pkgconfig:/home/robot/.julia/v0.5/Cbc/deps/usr/share/pkgconfig:/home/robot/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig:/home/robot/.julia/v0.5/Cbc/deps/usr/lib/pkgconfig \
pkg-config --libs osi > /home/robot/.julia/v0.5/Cbc/deps/usr/share/coin/doc/Osi/osi_addlibs.txt
make[4]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Osi'
make[3]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Osi'
make[2]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Osi'
make[1]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Osi'
Making install in Clp
make[1]: Entering directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Clp'
Making install in src
make[2]: Entering directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Clp/src'
if /bin/bash ../../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo .`  -I/usr/local/include/coin/ThirdParty -DCOIN_USE_MUMPS_MPI_H -I/usr/local/include/coin/ThirdParty -I/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -pedantic-errors -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -MT ClpCholeskyMumps.lo -MD -MP -MF ".deps/ClpCholeskyMumps.Tpo" -c -o ClpCholeskyMumps.lo ClpCholeskyMumps.cpp; \
then mv -f ".deps/ClpCholeskyMumps.Tpo" ".deps/ClpCholeskyMumps.Plo"; else rm -f ".deps/ClpCholeskyMumps.Tpo"; exit 1; fi
 g++ -DHAVE_CONFIG_H -I. -I. -I/usr/local/include/coin/ThirdParty -DCOIN_USE_MUMPS_MPI_H -I/usr/local/include/coin/ThirdParty -I/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -pedantic-errors -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -MT ClpCholeskyMumps.lo -MD -MP -MF .deps/ClpCholeskyMumps.Tpo -c ClpCholeskyMumps.cpp  -fPIC -DPIC -o .libs/ClpCholeskyMumps.o
ClpCholeskyMumps.cpp:17:17: fatal error: mpi.h: No such file or directory
compilation terminated.
Makefile:931: recipe for target 'ClpCholeskyMumps.lo' failed
make[2]: *** [ClpCholeskyMumps.lo] Error 1
make[2]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Clp/src'
Makefile:519: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/robot/.julia/v0.5/Cbc/deps/src/Cbc-2.9.8/Clp'
Makefile:323: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
===========================================[ ERROR: Cbc ]===========================================

LoadError: failed process: Process(`make install`, ProcessExited(2)) [2]
while loading /home/robot/.julia/v0.5/Cbc/deps/build.jl, in expression starting on line 62

====================================================================================================

```

**Comment by blegat** [comment]
It seems you are missing MPI headers, could you try doing
```
$ sudo apt-get install mpi-default-dev
$ julia -e 'Pkg.build("Cbc")'
```
and tell us if it worked ?

**Comment by yuzhangbit** [comment]
@blegat Thanks for your quick reply.  I tried your method. The same error still happens.

**Comment by blegat** [comment]
Did the installation work ? It should have also installed `libopenmpi-dev` as a dependency which has installed a file [mpi.h at `/usr/lib/openmpi/include/mpi.h`](http://packages.ubuntu.com/fr/trusty/amd64/libopenmpi-dev/filelist).
Can you check that it is indeed there with e.g. `$ ls /usr/lib/openmpi/include/mpi.h` ?

**Comment by mlubin** [comment]
It's probably finding a version of Mumps that requires MPI. If you don't need this, reinstall a version of Mumps that doesn't link against MPI.

**Comment by yuzhangbit** [comment]
@blegat  The installation worked.  But I still get the same error when installing Cbc in Julia.  
If I run `ls /usr/lib/openmpi/include/mpi.h`,  the output is 
```
/usr/lib/openmpi/include/mpi.h
```.
@mlubin  I do need Mumps for other optimization solvers.  If I install Cbc from source in C++, the installation(C++ version) works fine.  So I assume something is wrong with the julia Cbc deps build script.

**Comment by mlubin** [comment]
@yuzhangbit, the entire build script is [here](https://github.com/JuliaOpt/Cbc.jl/blob/59b815c07aa4165112743b6ebdbfc7095dfc8728/deps/build.jl#L57).

**Comment by yuzhangbit** [comment]
@mlubin Thanks for your information.

**Comment by blegat** [comment]
It seems that the issue is that `mpi.h` is not in `/usr/lib/openmpi/include` is scanned for by `g++` when looking for the header. You can see where it looks for by running
```
$ cpp -v /dev/null -o /dev/null
```
If you add `-I /usr/lib/openmpi/include` to the `g++` line that is failing, it should find `mpi.h`.
However, it is weird that you should do that since normally when you install a `-dev` package with apt-get, you should have to use `-I`... Have you tried to close your terminal and start a new one ?

**Comment by yuzhangbit** [comment]
Still can't resolve it.

**Comment by blegat** [comment]
You can try
```
$ ln -s /usr/lib/openmpi/include/mpi.h /usr/include
```
even if it's just a hack

**Comment by mlubin** [comment]
> If I install Cbc from source in C++, the installation(C++ version) works fine. So I assume something is wrong with the julia Cbc deps build script.
@yuzhangbit, can you reproduce the issue by building from source and using the Cbc.jl script that I pointed to?

**Comment by yuzhangbit** [comment]
@mlubin Yes.  By building Julia 0.5.1 from source and using the Cbc.jl, I can recreate the issue.

**Comment by mlubin** [comment]
@yuzhangbit, I meant building Cbc from source independent of Julia, as you said you had done before.

**Comment by yuzhangbit** [comment]
@blegat  Thanks for your information.  I tried.  It's not just 'mpi.h' file. If I hacked it in this way, the compiling asks for other mpi header files as well.  It's the whole mpi include directory that is not passed to the build script.

**Comment by blegat** [comment]
Then do
```
$ ln -s /usr/lib/openmpi/include /usr/include/openmpi
```

**Comment by mlubin** [comment]
The ubuntu cbc package ``coinor-libcbc-dev`` might also work. Just install it then run ``Pkg.build("Cbc")``.

**Comment by yuzhangbit** [comment]
@mlubin  Cool! Thanks a lot.  The `coinor-libcbc-dev` solves the problem.

**Comment by blegat** [comment]
@yuzhangbit glad to hear this. If you have the time, it would help us to know what is in the build script that makes Cbc not compile while when you compile it by hands it works.

**Comment by yuzhangbit** [comment]
@blegat Sure thing.  It's the `Clp/src` build script under the `Cbc-2.9.8` folder that can not find the include directory for the `mpi`.  I also notice that the [Cbc build] script((https://github.com/JuliaOpt/Cbc.jl/blob/master/deps/build.jl)) doesn't follow the exact instruction from the [Cbc website](https://projects.coin-or.org/Cbc).  The 
```
BuildTools/get.dependencies fetch
```
part is missing.
