### ISSUE TITLE
`getbasis` not implemented

### ISSUE THREAD

**Issue by matbesancon** [JuliaOpt/Cbc.jl#55]
From MathProgBase [documentation](http://mathprogbasejl.readthedocs.io/en/stable/lpqcqp.html#getbasis), `getbasis` must be defined for `AbstractLinearQuadraticModel`, but is not implemented here.

```julia
julia> internalmodel(m) isa MathProgBase.SolverInterface.AbstractLinearQuadraticModel
true

julia> MathProgBase.SolverInterface.getbasis(internalmodel(m))
ERROR: MethodError: no method matching getbasis(::Cbc.CbcMathProgSolverInterface.CbcMathProgModel)
Closest candidates are:
  getbasis(::Int64) at /home/mbesancon/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:29
  getbasis() at /home/mbesancon/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:27
```

**Comment by odow** [comment]
Not every method from MPB is implemented. PR's accepted :) If you wait, it it unlikely to get implemented given the upcoming change to MOI.

However, if you want it going forward, you may want to add the MOI versions (see [here](http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#MathOptInterface.BasisStatusCode)) to PR https://github.com/JuliaOpt/Cbc.jl/pull/54

**Comment by mlubin** [comment]
My initial guess is that this functionality does not exist in Cbc's C API.

**Comment by mbesancon** [comment]
thanks, given the answer do we close this issue? I'll ask on the Cbc mailing list for it and if there exists something in the C API, re-open

**Comment by odow** [comment]
This functionality doesn't exist in the current C Interface: https://github.com/coin-or/Cbc/blob/master/Cbc/src/Cbc_C_Interface.h

**Comment by matbesancon** [comment]
ok then, should we close this?
