### ISSUE TITLE
why always build from source?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/Cbc.jl#62]
Hello all, perhaps this is a dumb question but I was wondering why this always builds from source, even when there are perfectly good libraries that the linker sees just fine.  The compile process for this can be a bit on the long side.

I can make a PR to change the behavior to check for available libraries before building if there is not some reason why it always builds.

**Comment by mlubin** [comment]
We're intending to switch to BinaryBuilder soon, so all of this will change. But anyway I don't recall a reason not to use a system library if one is available.

**Comment by GunnarFarneback** [comment]
For what it's worth, at one point I had Cbc regularly crashing with Debian's version but work fine with a newer version built from source.

**Comment by ExpandingMan** [comment]
Sure, debian is a pain in the neck with being perpetually out of date (one of the reasons I'm trying to switch everything I do to Arch, still not quite there yet).  Still, it's probably uncontroversial to suggest that the default behavior should be to use system binaries if they exist, while always giving the user the option to compile from source.

**Comment by blegat** [comment]
The issue with system binaries is that they may use the wrong version. The solver wrapper target a specific API version. If there is a way to check the version in the `build.jl` file then I see no reason not to use the system binaries if available and of the right version.

**Comment by mlubin** [comment]
We use BinaryBuilder now.
