### ISSUE TITLE
How to set options with JuMP v0.19.x

### ISSUE THREAD

**Issue by JockLawrie** [JuliaOpt/Cbc.jl#79]
Hi there,

With JuMP v0.18.x and below I can set Cbc options with:
```julia
CbcSolver(seconds=5.0)
```

With JuMP v0.19 (alpha) I try the following and get a method error:
```julia
CbcOptimizer(seconds=5.0)
```
How do I set options with the `MathOptInterface`?

**Comment by mlubin** [comment]
Ping @vitornesello

**Comment by JockLawrie** [comment]
Ah, thanks
