### ISSUE TITLE
State of BinaryProvider build

### ISSUE THREAD

**Issue by ianfiske** [JuliaOpt/Cbc.jl#85]
Just curious about the status of moving to BinaryProvider.  @juan-pablo-vielma, you have https://github.com/juan-pablo-vielma/Cbc.jl/tree/jpv/bbmultigcc and there is no issues tab on that fork, so I'm asking here.  Is that branch an early-stage WIP or close to PR?  I'm wondering because I was going to try to make such a PR until I saw your existing efforts.

**Comment by juan-pablo-vielma** [comment]
It's pretty close to PR. I am hoping to have all COIN-OR solvers on BP by the end of the year.
