### ISSUE TITLE
"Modernize" the MOI wrapper

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Cbc.jl#88]
This package needs to be updated to MOI v0.7. In addition, there are a lot of things that should be fixed to keep up with other changes in MOI:
 - [ ] A large amount of the tests are excluded because the MOI wrapper doesn't support names: https://github.com/JuliaOpt/Cbc.jl/blob/master/test/MOIWrapper.jl
- [ ] There are lots of type-stability issues, e.g. https://github.com/JuliaOpt/Cbc.jl/blob/414499ee73b7679f4aff6b420a91ad270be8d87a/src/MOIWrapper.jl#L369-L372 which will return `nothing` instead of throwing an error.
- [ ] The wrapper should be updated to reflect the latest style guide

**Comment by mlubin** [comment]
The title is out of date given #91, but the points are still relevant.

**Comment by odow** [comment]
Closed by #108.
