### ISSUE TITLE
error compiling #CbcMathProgModel#2: could not load library "C:\Users\me\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libCbcSolver-3.DLL"

### ISSUE THREAD

**Issue by 3ch01c** [JuliaOpt/Cbc.jl#95]
# Problem
When this package is built, it looks like `deps/deps.jl` uses some environment-specific paths (e..g `C:\\Users\\me\\.julia\\v0.6`) to load dependencies.

```
# Load dependencies
@checked_lib libclp "C:\\Users\\me\\.julia\\v0.6\\WinRPM\\deps\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libClp-1.DLL"
@checked_lib libcbcsolver "C:\\Users\\me\\.julia\\v0.6\\WinRPM\\deps\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libCbcSolver-3.DLL"
```

This breaks when the package is used in an environment with a different [`JULIA_PKGDIR`](https://github.com/JuliaLang/julia/issues/19988#issuecomment-273255584) path than the environment in which it was built.

# Solution (Sort Of)
I tried replacing `C:\\Users\\me\\.julia\\v0.6` with `Base.Pkg.dir()` and `$JULIA_PKGDIR`, but that didn't seem to work. Not really sure if/how you can do variables/string concatenation here. The only workaround I could find was to edit the paths to be relative to `deps.jl`.
```
# Load dependencies
@checked_lib libclp "..\\..\\WinRPM\\deps\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libClp-1.DLL"
@checked_lib libcbcsolver "..\\..\\WinRPM\\deps\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libCbcSolver-3.DLL"
```
This will get overwritten next time I build the package, though.

# Other Notes
1. I'm new to Julia and expect there's a better way to do this, but I wanted to provide some breadcrumbs for anyone who might be in the same boat as me.
1. I think this is actually an issue with [BinDeps](https://github.com/JuliaPackaging/BinDeps.jl), but I haven't been able to figure out that package yet.
1. I didn't find any other packages with a section like this in their `deps.jl`. Maybe there's another way to include these libraries?

**Comment by odow** [comment]
We no longer support Cbc on Julia 0.6. You should update to Julia 1.0.

**Comment by odow** [comment]
Closing as stale. Please re-open if you have trouble installing Cbc on Julia 1.0.
